// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/core/judger_server/v1/server.proto

package judger_server

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpsertProblemRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertProblemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertProblemRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertProblemRequestMultiError, or nil if none found.
func (m *UpsertProblemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertProblemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProblemId

	// no validation rules for Name

	// no validation rules for Description

	if len(errors) > 0 {
		return UpsertProblemRequestMultiError(errors)
	}

	return nil
}

// UpsertProblemRequestMultiError is an error wrapping multiple validation
// errors returned by UpsertProblemRequest.ValidateAll() if the designated
// constraints aren't met.
type UpsertProblemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertProblemRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertProblemRequestMultiError) AllErrors() []error { return m }

// UpsertProblemRequestValidationError is the validation error returned by
// UpsertProblemRequest.Validate if the designated constraints aren't met.
type UpsertProblemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertProblemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertProblemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertProblemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertProblemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertProblemRequestValidationError) ErrorName() string {
	return "UpsertProblemRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertProblemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertProblemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertProblemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertProblemRequestValidationError{}

// Validate checks the field values on UpsertProblemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertProblemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertProblemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertProblemResponseMultiError, or nil if none found.
func (m *UpsertProblemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertProblemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetProblem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpsertProblemResponseValidationError{
					field:  "Problem",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpsertProblemResponseValidationError{
					field:  "Problem",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProblem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpsertProblemResponseValidationError{
				field:  "Problem",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpsertProblemResponseMultiError(errors)
	}

	return nil
}

// UpsertProblemResponseMultiError is an error wrapping multiple validation
// errors returned by UpsertProblemResponse.ValidateAll() if the designated
// constraints aren't met.
type UpsertProblemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertProblemResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertProblemResponseMultiError) AllErrors() []error { return m }

// UpsertProblemResponseValidationError is the validation error returned by
// UpsertProblemResponse.Validate if the designated constraints aren't met.
type UpsertProblemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertProblemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertProblemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertProblemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertProblemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertProblemResponseValidationError) ErrorName() string {
	return "UpsertProblemResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertProblemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertProblemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertProblemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertProblemResponseValidationError{}

// Validate checks the field values on ProblemResponseData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProblemResponseData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProblemResponseData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProblemResponseDataMultiError, or nil if none found.
func (m *ProblemResponseData) ValidateAll() error {
	return m.validate(true)
}

func (m *ProblemResponseData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProblemId

	if len(errors) > 0 {
		return ProblemResponseDataMultiError(errors)
	}

	return nil
}

// ProblemResponseDataMultiError is an error wrapping multiple validation
// errors returned by ProblemResponseData.ValidateAll() if the designated
// constraints aren't met.
type ProblemResponseDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProblemResponseDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProblemResponseDataMultiError) AllErrors() []error { return m }

// ProblemResponseDataValidationError is the validation error returned by
// ProblemResponseData.Validate if the designated constraints aren't met.
type ProblemResponseDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProblemResponseDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProblemResponseDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProblemResponseDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProblemResponseDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProblemResponseDataValidationError) ErrorName() string {
	return "ProblemResponseDataValidationError"
}

// Error satisfies the builtin error interface
func (e ProblemResponseDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProblemResponseData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProblemResponseDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProblemResponseDataValidationError{}

// Validate checks the field values on UpsertContestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertContestRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertContestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertContestRequestMultiError, or nil if none found.
func (m *UpsertContestRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertContestRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContestId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for StartTime

	// no validation rules for EndTime

	if len(errors) > 0 {
		return UpsertContestRequestMultiError(errors)
	}

	return nil
}

// UpsertContestRequestMultiError is an error wrapping multiple validation
// errors returned by UpsertContestRequest.ValidateAll() if the designated
// constraints aren't met.
type UpsertContestRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertContestRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertContestRequestMultiError) AllErrors() []error { return m }

// UpsertContestRequestValidationError is the validation error returned by
// UpsertContestRequest.Validate if the designated constraints aren't met.
type UpsertContestRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertContestRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertContestRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertContestRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertContestRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertContestRequestValidationError) ErrorName() string {
	return "UpsertContestRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertContestRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertContestRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertContestRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertContestRequestValidationError{}

// Validate checks the field values on UpsertContestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertContestResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertContestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertContestResponseMultiError, or nil if none found.
func (m *UpsertContestResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertContestResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetContest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpsertContestResponseValidationError{
					field:  "Contest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpsertContestResponseValidationError{
					field:  "Contest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpsertContestResponseValidationError{
				field:  "Contest",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpsertContestResponseMultiError(errors)
	}

	return nil
}

// UpsertContestResponseMultiError is an error wrapping multiple validation
// errors returned by UpsertContestResponse.ValidateAll() if the designated
// constraints aren't met.
type UpsertContestResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertContestResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertContestResponseMultiError) AllErrors() []error { return m }

// UpsertContestResponseValidationError is the validation error returned by
// UpsertContestResponse.Validate if the designated constraints aren't met.
type UpsertContestResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertContestResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertContestResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertContestResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertContestResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertContestResponseValidationError) ErrorName() string {
	return "UpsertContestResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertContestResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertContestResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertContestResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertContestResponseValidationError{}

// Validate checks the field values on ContestResponseData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ContestResponseData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ContestResponseData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ContestResponseDataMultiError, or nil if none found.
func (m *ContestResponseData) ValidateAll() error {
	return m.validate(true)
}

func (m *ContestResponseData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContestId

	if len(errors) > 0 {
		return ContestResponseDataMultiError(errors)
	}

	return nil
}

// ContestResponseDataMultiError is an error wrapping multiple validation
// errors returned by ContestResponseData.ValidateAll() if the designated
// constraints aren't met.
type ContestResponseDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContestResponseDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContestResponseDataMultiError) AllErrors() []error { return m }

// ContestResponseDataValidationError is the validation error returned by
// ContestResponseData.Validate if the designated constraints aren't met.
type ContestResponseDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContestResponseDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContestResponseDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContestResponseDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContestResponseDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContestResponseDataValidationError) ErrorName() string {
	return "ContestResponseDataValidationError"
}

// Error satisfies the builtin error interface
func (e ContestResponseDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContestResponseData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContestResponseDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContestResponseDataValidationError{}

// Validate checks the field values on SubmitRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SubmitRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SubmitRequestMultiError, or
// nil if none found.
func (m *SubmitRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProblemId

	// no validation rules for Language

	// no validation rules for Code

	// no validation rules for Input

	// no validation rules for Output

	// no validation rules for TestCaseId

	if len(errors) > 0 {
		return SubmitRequestMultiError(errors)
	}

	return nil
}

// SubmitRequestMultiError is an error wrapping multiple validation errors
// returned by SubmitRequest.ValidateAll() if the designated constraints
// aren't met.
type SubmitRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitRequestMultiError) AllErrors() []error { return m }

// SubmitRequestValidationError is the validation error returned by
// SubmitRequest.Validate if the designated constraints aren't met.
type SubmitRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitRequestValidationError) ErrorName() string { return "SubmitRequestValidationError" }

// Error satisfies the builtin error interface
func (e SubmitRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitRequestValidationError{}

// Validate checks the field values on SubmitResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SubmitResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SubmitResponseMultiError,
// or nil if none found.
func (m *SubmitResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetSubmit()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitResponseValidationError{
					field:  "Submit",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitResponseValidationError{
					field:  "Submit",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSubmit()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitResponseValidationError{
				field:  "Submit",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SubmitResponseMultiError(errors)
	}

	return nil
}

// SubmitResponseMultiError is an error wrapping multiple validation errors
// returned by SubmitResponse.ValidateAll() if the designated constraints
// aren't met.
type SubmitResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitResponseMultiError) AllErrors() []error { return m }

// SubmitResponseValidationError is the validation error returned by
// SubmitResponse.Validate if the designated constraints aren't met.
type SubmitResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitResponseValidationError) ErrorName() string { return "SubmitResponseValidationError" }

// Error satisfies the builtin error interface
func (e SubmitResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitResponseValidationError{}

// Validate checks the field values on SubmitResponseData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmitResponseData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitResponseData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitResponseDataMultiError, or nil if none found.
func (m *SubmitResponseData) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitResponseData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubmissionId

	// no validation rules for Status

	// no validation rules for Score

	// no validation rules for Time

	// no validation rules for Memory

	if len(errors) > 0 {
		return SubmitResponseDataMultiError(errors)
	}

	return nil
}

// SubmitResponseDataMultiError is an error wrapping multiple validation errors
// returned by SubmitResponseData.ValidateAll() if the designated constraints
// aren't met.
type SubmitResponseDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitResponseDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitResponseDataMultiError) AllErrors() []error { return m }

// SubmitResponseDataValidationError is the validation error returned by
// SubmitResponseData.Validate if the designated constraints aren't met.
type SubmitResponseDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitResponseDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitResponseDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitResponseDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitResponseDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitResponseDataValidationError) ErrorName() string {
	return "SubmitResponseDataValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitResponseDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitResponseData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitResponseDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitResponseDataValidationError{}
