load("@rules_oci//oci:defs.bzl", "oci_image", "oci_tarball")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "server_tar",
    srcs = ["//src/apps/backend/server/cmd"],
)

oci_image(
    name = "image",
    base = "@distroless_static",
    entrypoint = ["/server"],
    tars = [":server_tar"],
)

oci_tarball(
    name = "tarball",
    image = ":image",
    repo_tags = ["online-judge/server:latest"],
)
