load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "handler",
    srcs = ["judger_handler.go"],
    importpath = "github.com/Nanhtu187/online-judge/src/apps/backend/runner/internal/handler",
    visibility = ["//src/apps/backend/runner:__subpackages__"],
    deps = [
        "//src/apps/backend/runner/internal/service",
        "//src/packages/kafka",
        "@com_github_segmentio_kafka_go//:kafka-go",
    ],
)
