load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "handler",
    srcs = ["iam_handler.go"],
    importpath = "github.com/Nanhtu187/online-judge/src/apps/backend/iam/internal/handler",
    visibility = ["//src/apps/backend/iam:__subpackages__"],
    deps = [
        "//src/apps/backend/iam/internal/service",
        "//src/packages/proto/gen/go/iam",
        "@com_github_golang_jwt_jwt_v5//:jwt",
        "@org_golang_google_grpc//metadata",
    ],
)
