// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/iam/v1/common.proto

package iam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pagination...
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_proto_iam_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// CommonAsyncResponse ...
type CommonAsyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code ...
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// message ...
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonAsyncResponse) Reset() {
	*x = CommonAsyncResponse{}
	mi := &file_proto_iam_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonAsyncResponse) ProtoMessage() {}

func (x *CommonAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonAsyncResponse.ProtoReflect.Descriptor instead.
func (*CommonAsyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *CommonAsyncResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonAsyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_iam_v1_common_proto protoreflect.FileDescriptor

const file_proto_iam_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19proto/iam/v1/common.proto\x12\x06iam.v1\"S\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"C\n" +
	"\x13CommonAsyncResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x0fZ\rproto/rpc/iamb\x06proto3"

var (
	file_proto_iam_v1_common_proto_rawDescOnce sync.Once
	file_proto_iam_v1_common_proto_rawDescData []byte
)

func file_proto_iam_v1_common_proto_rawDescGZIP() []byte {
	file_proto_iam_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_iam_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iam_v1_common_proto_rawDesc), len(file_proto_iam_v1_common_proto_rawDesc)))
	})
	return file_proto_iam_v1_common_proto_rawDescData
}

var file_proto_iam_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_iam_v1_common_proto_goTypes = []any{
	(*Pagination)(nil),          // 0: iam.v1.Pagination
	(*CommonAsyncResponse)(nil), // 1: iam.v1.CommonAsyncResponse
}
var file_proto_iam_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_iam_v1_common_proto_init() }
func file_proto_iam_v1_common_proto_init() {
	if File_proto_iam_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iam_v1_common_proto_rawDesc), len(file_proto_iam_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_iam_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_iam_v1_common_proto_depIdxs,
		MessageInfos:      file_proto_iam_v1_common_proto_msgTypes,
	}.Build()
	File_proto_iam_v1_common_proto = out.File
	file_proto_iam_v1_common_proto_goTypes = nil
	file_proto_iam_v1_common_proto_depIdxs = nil
}
