// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/iam/v1/iam.proto

package iam

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	School        string                 `protobuf:"bytes,4,opt,name=school,proto3" json:"school,omitempty"`
	Class         string                 `protobuf:"bytes,5,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserRequest) Reset() {
	*x = UpsertUserRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserRequest) ProtoMessage() {}

func (x *UpsertUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserRequest.ProtoReflect.Descriptor instead.
func (*UpsertUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpsertUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpsertUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertUserRequest) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *UpsertUserRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

type UpsertUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CreateUserData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserResponse) Reset() {
	*x = UpsertUserResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserResponse) ProtoMessage() {}

func (x *UpsertUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserResponse.ProtoReflect.Descriptor instead.
func (*UpsertUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpsertUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertUserResponse) GetData() *CreateUserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserData) Reset() {
	*x = CreateUserData{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserData) ProtoMessage() {}

func (x *CreateUserData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserData.ProtoReflect.Descriptor instead.
func (*CreateUserData) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserData) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LoginData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{7}
}

func (x *LoginData) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{8}
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RefreshTokenData      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RefreshTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefreshTokenResponse) GetData() *RefreshTokenData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RefreshTokenData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenData) Reset() {
	*x = RefreshTokenData{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenData) ProtoMessage() {}

func (x *RefreshTokenData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenData.ProtoReflect.Descriptor instead.
func (*RefreshTokenData) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenData) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	School        string                 `protobuf:"bytes,2,opt,name=school,proto3" json:"school,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListUserRequest) Reset() {
	*x = GetListUserRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListUserRequest) ProtoMessage() {}

func (x *GetListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListUserRequest.ProtoReflect.Descriptor instead.
func (*GetListUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{11}
}

func (x *GetListUserRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetListUserRequest) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *GetListUserRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *GetListUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListUserRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetListUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetListUserData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListUserResponse) Reset() {
	*x = GetListUserResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListUserResponse) ProtoMessage() {}

func (x *GetListUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListUserResponse.ProtoReflect.Descriptor instead.
func (*GetListUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{12}
}

func (x *GetListUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetListUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetListUserResponse) GetData() *GetListUserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetListUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserData            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListUserData) Reset() {
	*x = GetListUserData{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListUserData) ProtoMessage() {}

func (x *GetListUserData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListUserData.ProtoReflect.Descriptor instead.
func (*GetListUserData) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{13}
}

func (x *GetListUserData) GetUsers() []*UserData {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetListUserData) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	School        string                 `protobuf:"bytes,3,opt,name=school,proto3" json:"school,omitempty"`
	Class         string                 `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{14}
}

func (x *UserData) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserData) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *UserData) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCurrentUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserInfoRequest) Reset() {
	*x = GetCurrentUserInfoRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserInfoRequest) ProtoMessage() {}

func (x *GetCurrentUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{17}
}

type GetCurrentUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserInfoResponse) Reset() {
	*x = GetCurrentUserInfoResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserInfoResponse) ProtoMessage() {}

func (x *GetCurrentUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{18}
}

func (x *GetCurrentUserInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCurrentUserInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCurrentUserInfoResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_iam_v1_iam_proto protoreflect.FileDescriptor

const file_proto_iam_v1_iam_proto_rawDesc = "" +
	"\n" +
	"\x16proto/iam/v1/iam.proto\x12\x06iam.v1\x1a\x13iam/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xb3\x01\n" +
	"\x11UpsertUserRequest\x12%\n" +
	"\busername\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x14R\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18\x1eR\x04name\x12\x1f\n" +
	"\x06school\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x18dR\x06school\x12\x1d\n" +
	"\x05class\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x18\x1eR\x05class\"n\n" +
	"\x12UpsertUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.iam.v1.CreateUserDataR\x04data\"*\n" +
	"\x0eCreateUserData\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\x05R\auser_id\"F\n" +
	"\x0eGetUserRequest\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\x05R\auser_id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"e\n" +
	"\x0fGetUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.iam.v1.UserDataR\x04data\"Z\n" +
	"\fLoginRequest\x12%\n" +
	"\busername\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x14R\busername\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\bR\bpassword\"d\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x04data\x18\x03 \x01(\v2\x11.iam.v1.LoginDataR\x04data\"/\n" +
	"\tLoginData\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\"\x15\n" +
	"\x13RefreshTokenRequest\"r\n" +
	"\x14RefreshTokenResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x04data\x18\x03 \x01(\v2\x18.iam.v1.RefreshTokenDataR\x04data\"6\n" +
	"\x10RefreshTokenData\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\"\x8e\x01\n" +
	"\x12GetListUserRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06school\x18\x02 \x01(\tR\x06school\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1c\n" +
	"\tpage_size\x18\x05 \x01(\x05R\tpage_size\"p\n" +
	"\x13GetListUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.iam.v1.GetListUserDataR\x04data\"m\n" +
	"\x0fGetListUserData\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.iam.v1.UserDataR\x05users\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.iam.v1.PaginationR\n" +
	"pagination\"f\n" +
	"\bUserData\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\x05R\auser_id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06school\x18\x03 \x01(\tR\x06school\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\"6\n" +
	"\x11DeleteUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\auser_id\"B\n" +
	"\x12DeleteUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1b\n" +
	"\x19GetCurrentUserInfoRequest\"p\n" +
	"\x1aGetCurrentUserInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.iam.v1.UserDataR\x04data2\xc1\x05\n" +
	"\n" +
	"IamService\x12]\n" +
	"\n" +
	"UpsertUser\x12\x19.iam.v1.UpsertUserRequest\x1a\x1a.iam.v1.UpsertUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12[\n" +
	"\aGetUser\x12\x16.iam.v1.GetUserRequest\x1a\x17.iam.v1.GetUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/users/{user_id}\x12N\n" +
	"\x05Login\x12\x14.iam.v1.LoginRequest\x1a\x15.iam.v1.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12k\n" +
	"\fRefreshToken\x12\x1b.iam.v1.RefreshTokenRequest\x1a\x1c.iam.v1.RefreshTokenResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/refresh-token\x12]\n" +
	"\vGetListUser\x12\x1a.iam.v1.GetListUserRequest\x1a\x1b.iam.v1.GetListUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12d\n" +
	"\n" +
	"DeleteUser\x12\x19.iam.v1.DeleteUserRequest\x1a\x1a.iam.v1.DeleteUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/users/{user_id}\x12u\n" +
	"\x12GetCurrentUserInfo\x12!.iam.v1.GetCurrentUserInfoRequest\x1a\".iam.v1.GetCurrentUserInfoResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/users/meB\x0fZ\rproto/rpc/iamb\x06proto3"

var (
	file_proto_iam_v1_iam_proto_rawDescOnce sync.Once
	file_proto_iam_v1_iam_proto_rawDescData []byte
)

func file_proto_iam_v1_iam_proto_rawDescGZIP() []byte {
	file_proto_iam_v1_iam_proto_rawDescOnce.Do(func() {
		file_proto_iam_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iam_v1_iam_proto_rawDesc), len(file_proto_iam_v1_iam_proto_rawDesc)))
	})
	return file_proto_iam_v1_iam_proto_rawDescData
}

var file_proto_iam_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_iam_v1_iam_proto_goTypes = []any{
	(*UpsertUserRequest)(nil),          // 0: iam.v1.UpsertUserRequest
	(*UpsertUserResponse)(nil),         // 1: iam.v1.UpsertUserResponse
	(*CreateUserData)(nil),             // 2: iam.v1.CreateUserData
	(*GetUserRequest)(nil),             // 3: iam.v1.GetUserRequest
	(*GetUserResponse)(nil),            // 4: iam.v1.GetUserResponse
	(*LoginRequest)(nil),               // 5: iam.v1.LoginRequest
	(*LoginResponse)(nil),              // 6: iam.v1.LoginResponse
	(*LoginData)(nil),                  // 7: iam.v1.LoginData
	(*RefreshTokenRequest)(nil),        // 8: iam.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),       // 9: iam.v1.RefreshTokenResponse
	(*RefreshTokenData)(nil),           // 10: iam.v1.RefreshTokenData
	(*GetListUserRequest)(nil),         // 11: iam.v1.GetListUserRequest
	(*GetListUserResponse)(nil),        // 12: iam.v1.GetListUserResponse
	(*GetListUserData)(nil),            // 13: iam.v1.GetListUserData
	(*UserData)(nil),                   // 14: iam.v1.UserData
	(*DeleteUserRequest)(nil),          // 15: iam.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),         // 16: iam.v1.DeleteUserResponse
	(*GetCurrentUserInfoRequest)(nil),  // 17: iam.v1.GetCurrentUserInfoRequest
	(*GetCurrentUserInfoResponse)(nil), // 18: iam.v1.GetCurrentUserInfoResponse
	(*Pagination)(nil),                 // 19: iam.v1.Pagination
}
var file_proto_iam_v1_iam_proto_depIdxs = []int32{
	2,  // 0: iam.v1.UpsertUserResponse.data:type_name -> iam.v1.CreateUserData
	14, // 1: iam.v1.GetUserResponse.data:type_name -> iam.v1.UserData
	7,  // 2: iam.v1.LoginResponse.data:type_name -> iam.v1.LoginData
	10, // 3: iam.v1.RefreshTokenResponse.data:type_name -> iam.v1.RefreshTokenData
	13, // 4: iam.v1.GetListUserResponse.data:type_name -> iam.v1.GetListUserData
	14, // 5: iam.v1.GetListUserData.users:type_name -> iam.v1.UserData
	19, // 6: iam.v1.GetListUserData.pagination:type_name -> iam.v1.Pagination
	14, // 7: iam.v1.GetCurrentUserInfoResponse.data:type_name -> iam.v1.UserData
	0,  // 8: iam.v1.IamService.UpsertUser:input_type -> iam.v1.UpsertUserRequest
	3,  // 9: iam.v1.IamService.GetUser:input_type -> iam.v1.GetUserRequest
	5,  // 10: iam.v1.IamService.Login:input_type -> iam.v1.LoginRequest
	8,  // 11: iam.v1.IamService.RefreshToken:input_type -> iam.v1.RefreshTokenRequest
	11, // 12: iam.v1.IamService.GetListUser:input_type -> iam.v1.GetListUserRequest
	15, // 13: iam.v1.IamService.DeleteUser:input_type -> iam.v1.DeleteUserRequest
	17, // 14: iam.v1.IamService.GetCurrentUserInfo:input_type -> iam.v1.GetCurrentUserInfoRequest
	1,  // 15: iam.v1.IamService.UpsertUser:output_type -> iam.v1.UpsertUserResponse
	4,  // 16: iam.v1.IamService.GetUser:output_type -> iam.v1.GetUserResponse
	6,  // 17: iam.v1.IamService.Login:output_type -> iam.v1.LoginResponse
	9,  // 18: iam.v1.IamService.RefreshToken:output_type -> iam.v1.RefreshTokenResponse
	12, // 19: iam.v1.IamService.GetListUser:output_type -> iam.v1.GetListUserResponse
	16, // 20: iam.v1.IamService.DeleteUser:output_type -> iam.v1.DeleteUserResponse
	18, // 21: iam.v1.IamService.GetCurrentUserInfo:output_type -> iam.v1.GetCurrentUserInfoResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_iam_v1_iam_proto_init() }
func file_proto_iam_v1_iam_proto_init() {
	if File_proto_iam_v1_iam_proto != nil {
		return
	}
	file_iam_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iam_v1_iam_proto_rawDesc), len(file_proto_iam_v1_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iam_v1_iam_proto_goTypes,
		DependencyIndexes: file_proto_iam_v1_iam_proto_depIdxs,
		MessageInfos:      file_proto_iam_v1_iam_proto_msgTypes,
	}.Build()
	File_proto_iam_v1_iam_proto = out.File
	file_proto_iam_v1_iam_proto_goTypes = nil
	file_proto_iam_v1_iam_proto_depIdxs = nil
}
