syntax = "proto3";
package judger_server.v1;

// import "judger_server/v1/common.proto";
import "google/api/annotations.proto";
import "validate/validate.proto";
option go_package = "proto/rpc/judger_server";

service JudgerService {
    // Upsert Problem ...
    rpc UpsertProblem(UpsertProblemRequest) returns (UpsertProblemResponse) {
      option (google.api.http) = {
        post: "/api/v1/problems"
        body: "*"
      };
    }

    // Get Problem ...
    rpc GetProblem(GetProblemRequest) returns (GetProblemResponse) {
      option (google.api.http) = {
        get: "/api/v1/problems/{problem_id}"
      };
    }

    // Get List Problems ...
    rpc GetListProblems(GetListProblemsRequest) returns (GetListProblemsResponse) {
      option (google.api.http) = {
        get: "/api/v1/problems"
      };
    }

    // Upsert Contest ...
    rpc UpsertContest(UpsertContestRequest) returns (UpsertContestResponse) {
        option (google.api.http) = {
          post: "/api/v1/contests"
          body: "*"
        };
    }

    // Get Contest ...
    rpc GetContest(GetContestRequest) returns (GetContestResponse) {
      option (google.api.http) = {
        get: "/api/v1/contests/{contest_id}"
      };
    }

    // Get List Contests ...
    rpc GetListContests(GetListContestsRequest) returns (GetListContestsResponse) {
      option (google.api.http) = {
        get: "/api/v1/contests"
      };
    }

    // UpsertSubmission ...
    rpc UpsertSubmission(UpsertSubmissionRequest) returns (UpsertSubmissionResponse) {
        option (google.api.http) = {
          post: "/api/v1/submissions"
          body: "*"
        };
    }

    // Get Submission ...
    rpc GetSubmission(GetSubmissionRequest) returns (GetSubmissionResponse) {
      option (google.api.http) = {
        get: "/api/v1/submissions/{submission_id}"
      };
    }

    // Get List Submissions ...
    rpc GetListSubmissions(GetListSubmissionsRequest) returns (GetListSubmissionsResponse) {
      option (google.api.http) = {
        get: "/api/v1/submissions"
      };
    }

    // Get List Results ...
    rpc GetListResults(GetListResultsRequest) returns (GetListResultsResponse) {
      option (google.api.http) = {
        get: "/api/v1/results"
      };
    }

    // Get Result ...
    rpc GetResult(GetResultRequest) returns (GetResultResponse) {
      option (google.api.http) = {
        get: "/api/v1/results/{result_id}"
      };
    }
}

message UpsertProblemRequest {
    // Problem ID
    int32 problem_id = 1 [json_name="problemId"];

    // Problem Name
    string name = 2 [json_name="name"];

    // Problem Description
    string description = 3 [json_name="description"];


}

message UpsertProblemResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    UpsertProblemResponseData data = 3 [json_name="data"];
}

message UpsertProblemResponseData {
    // Problem ID
    int32 problem_id = 1 [json_name="problemId"];
}

message UpsertContestRequest {
    // Contest ID
    int32 contest_id = 1 [json_name="contestId"];

    // Contest Name
    string name = 2 [json_name="name"];

    // Contest Description
    string description = 3 [json_name="description"];

    // Start Time
    int64 start_time = 4 [json_name="startTime"];

    // End Time
    int64 end_time = 5 [json_name="endTime"];

    // Problem IDs
    repeated int32 problem_ids = 6 [json_name="problemIds"];
    
}

message UpsertContestResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    ContestResponseData contest = 3 [json_name="contest"];
}

message ContestResponseData {
    // Contest ID
    int32 contest_id = 1 [json_name="contestId"];
}

message UpsertSubmissionRequest {
    // Problem ID
    int32 problem_id = 1 [json_name="problemId"];

    // Contest ID
    int32 contest_id = 2 [json_name="contestId"];

    // User ID
    int32 user_id = 3 [json_name="userId"];

    // Language
    string language = 4 [json_name="language"];

    // Code
    string code = 5 [json_name="code"];

}

message UpsertSubmissionResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    UpsertSubmissionResponseData data = 3 [json_name="data"];
}

message UpsertSubmissionResponseData {
    // Submission ID
    int32 submission_id = 1 [json_name="submitId"];

    // Status
    string status = 2 [json_name="status"];

    // Score
    int32 score = 3 [json_name="score"];

    // Time
    int32 time = 4 [json_name="time"];

    // Memory
    int32 memory = 5 [json_name="memory"];
}

message Problem {
    // Problem ID
    int32 problem_id = 1 [json_name="problemId"];

    // Problem Name
    string name = 2 [json_name="name"];

    // Problem Description
    string description = 3 [json_name="description"];
}

message GetProblemRequest {
    // Problem ID
    int32 problem_id = 1 [json_name="problemId"];
}

message GetProblemResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    Problem problem = 3 [json_name="problem"];
}

message GetListProblemsRequest {
    // Page Number
    int32 page = 1 [json_name="page"];

    // Page Size
    int32 page_size = 2 [json_name="pageSize"];

    // Keyword
    string keyword = 3 [json_name="keyword"];
}

message GetListProblemsResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    GetListProblemsResponseData data = 3 [json_name="data"];
}

message ListProblemResponseData {
    // Problem ID
    int32 problem_id = 1 [json_name="problemId"];
    // Problem Title
    string title = 2 [json_name="title"];
}

message GetListProblemsResponseData {
    repeated ListProblemResponseData problems = 1 [json_name="problems"];
    int32 total = 2 [json_name="total"];
    int32 page = 3 [json_name="page"];
    int32 page_size = 4 [json_name="pageSize"];
}

message GetContestRequest {
    // Contest ID
    int32 contest_id = 1 [json_name="contestId"];

    // Keyword
    string keyword = 2 [json_name="keyword"];
}

message GetContestResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    Contest data = 3 [json_name="data"];
}

message Contest {
    // Contest ID
    int32 contest_id = 1 [json_name="contestId"];

    // Contest Name
    string name = 2 [json_name="name"];

    // Contest Description
    string description = 3 [json_name="description"];

    // Start Time
    int64 start_time = 4 [json_name="startTime"];

    // End Time
    int64 end_time = 5 [json_name="endTime"];

    // Problem IDs
    repeated int32 problem_ids = 6 [json_name="problemIds"];
}

message GetListContestsRequest {
    // Page Number
    int32 page = 1 [json_name="page"];

    // Page Size
    int32 page_size = 2 [json_name="pageSize"];

    // Keyword
    string keyword = 3 [json_name="keyword"];
}

message GetListContestsResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    GetListContestsResponseData data = 3 [json_name="data"];
}

message ListContestResponseData {
    // Contest ID
    int32 contest_id = 1 [json_name="contestId"];
    // Contest Title
    string title = 2 [json_name="title"];
}

message GetListContestsResponseData {
    repeated ListContestResponseData contests = 1 [json_name="contests"];
    int32 total = 2 [json_name="total"];
    int32 page = 3 [json_name="page"];
    int32 page_size = 4 [json_name="pageSize"];
}

message GetSubmissionRequest {
    // Submission ID
    int32 submission_id = 1 [json_name="submissionId"];
}

message GetSubmissionResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    Submission data = 3 [json_name="data"];
}

message Submission {
    // Submission ID
    int32 submission_id = 1 [json_name="submissionId"];

    // Problem ID
    int32 problem_id = 2 [json_name="problemId"];

    // Language
    string language = 3 [json_name="language"];

    // Code
    string code = 4 [json_name="code"];

    // Input
    string input = 5 [json_name="input"];

    // Output
    string output = 6 [json_name="output"];

    // Test Case ID
    int32 test_case_id = 7 [json_name="testCaseId"];
}

message GetListSubmissionsRequest {
    // Page Number
    int32 page = 1 [json_name="page"];

    // Page Size
    int32 page_size = 2 [json_name="pageSize"];

    // Keyword
    string keyword = 3 [json_name="keyword"];
}

message GetListSubmissionsResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    GetListSubmissionsResponseData data = 3 [json_name="data"];
}

message ListSubmissionResponseData {
    // Submission ID
    int32 submission_id = 1 [json_name="submissionId"];
}

message GetListSubmissionsResponseData {
    repeated ListSubmissionResponseData submissions = 1 [json_name="submissions"];
    int32 total = 2 [json_name="total"];
    int32 page = 3 [json_name="page"];
    int32 page_size = 4 [json_name="pageSize"];
}

message GetResultRequest {
    // Result ID
    int32 result_id = 1 [json_name="resultId"];
}

message GetResultResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    Result data = 3 [json_name="data"];
}

message Result {
    // Result ID
    int32 result_id = 1 [json_name="resultId"];

    // Problem ID
    int32 problem_id = 2 [json_name="problemId"];

    // Language
    string language = 3 [json_name="language"];

    // Code
    string code = 4 [json_name="code"];

    // Input
    string input = 5 [json_name="input"];

    // Output
    string output = 6 [json_name="output"];

    // Test Case ID
    int32 test_case_id = 7 [json_name="testCaseId"];
}

message GetListResultsRequest {
    // Page Number
    int32 page = 1 [json_name="page"];

    // Page Size
    int32 page_size = 2 [json_name="pageSize"];

    // user_id
    int32 user_id = 3 [json_name="user_id"];

}

message GetListResultsResponse {
    // code ...
    int32 code = 1 [json_name="code"];
    // message ...
    string message = 2 [json_name="message"];
    // data ...
    GetListResultsResponseData data = 3 [json_name="data"];
}
message ListResultResponseData {
    // Result ID
    int32 result_id = 1 [json_name="resultId"];
}

message GetListResultsResponseData {
    repeated ListResultResponseData results = 1 [json_name="results"];
    int32 total = 2 [json_name="total"];
    int32 page = 3 [json_name="page"];
    int32 page_size = 4 [json_name="pageSize"];
}