// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/core/judger_server/v1/server.proto

package judger_server

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertProblemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Problem ID
	ProblemId int32 `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	// Problem Name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Problem Description
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProblemRequest) Reset() {
	*x = UpsertProblemRequest{}
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProblemRequest) ProtoMessage() {}

func (x *UpsertProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProblemRequest.ProtoReflect.Descriptor instead.
func (*UpsertProblemRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_judger_server_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertProblemRequest) GetProblemId() int32 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *UpsertProblemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertProblemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpsertProblemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code ...
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// message ...
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// data ...
	Data          *ProblemResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProblemResponse) Reset() {
	*x = UpsertProblemResponse{}
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProblemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProblemResponse) ProtoMessage() {}

func (x *UpsertProblemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProblemResponse.ProtoReflect.Descriptor instead.
func (*UpsertProblemResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_judger_server_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertProblemResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpsertProblemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertProblemResponse) GetData() *ProblemResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProblemResponseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Problem ID
	ProblemId     int32 `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemResponseData) Reset() {
	*x = ProblemResponseData{}
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemResponseData) ProtoMessage() {}

func (x *ProblemResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemResponseData.ProtoReflect.Descriptor instead.
func (*ProblemResponseData) Descriptor() ([]byte, []int) {
	return file_proto_core_judger_server_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *ProblemResponseData) GetProblemId() int32 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

type UpsertContestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contest ID
	ContestId int32 `protobuf:"varint,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	// Contest Name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Contest Description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Start Time
	StartTime int64 `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End Time
	EndTime int64 `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Problem IDs
	ProblemIds    []int32 `protobuf:"varint,6,rep,packed,name=problem_ids,json=problemIds,proto3" json:"problem_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertContestRequest) Reset() {
	*x = UpsertContestRequest{}
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertContestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertContestRequest) ProtoMessage() {}

func (x *UpsertContestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertContestRequest.ProtoReflect.Descriptor instead.
func (*UpsertContestRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_judger_server_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertContestRequest) GetContestId() int32 {
	if x != nil {
		return x.ContestId
	}
	return 0
}

func (x *UpsertContestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertContestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpsertContestRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpsertContestRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *UpsertContestRequest) GetProblemIds() []int32 {
	if x != nil {
		return x.ProblemIds
	}
	return nil
}

type UpsertContestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code ...
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// message ...
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// data ...
	Contest       *ContestResponseData `protobuf:"bytes,3,opt,name=contest,proto3" json:"contest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertContestResponse) Reset() {
	*x = UpsertContestResponse{}
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertContestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertContestResponse) ProtoMessage() {}

func (x *UpsertContestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertContestResponse.ProtoReflect.Descriptor instead.
func (*UpsertContestResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_judger_server_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertContestResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpsertContestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertContestResponse) GetContest() *ContestResponseData {
	if x != nil {
		return x.Contest
	}
	return nil
}

type ContestResponseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contest ID
	ContestId     int32 `protobuf:"varint,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestResponseData) Reset() {
	*x = ContestResponseData{}
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestResponseData) ProtoMessage() {}

func (x *ContestResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestResponseData.ProtoReflect.Descriptor instead.
func (*ContestResponseData) Descriptor() ([]byte, []int) {
	return file_proto_core_judger_server_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *ContestResponseData) GetContestId() int32 {
	if x != nil {
		return x.ContestId
	}
	return 0
}

type SubmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Problem ID
	ProblemId int32 `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	// Language
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Code
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// Input
	Input string `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	// Output
	Output string `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	// Test Case ID
	TestCaseId    int32 `protobuf:"varint,6,opt,name=test_case_id,json=testCaseId,proto3" json:"test_case_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_judger_server_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitRequest) GetProblemId() int32 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *SubmitRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubmitRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SubmitRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *SubmitRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *SubmitRequest) GetTestCaseId() int32 {
	if x != nil {
		return x.TestCaseId
	}
	return 0
}

type SubmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code ...
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// message ...
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// data ...
	Submit        *SubmitResponseData `protobuf:"bytes,3,opt,name=submit,proto3" json:"submit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_judger_server_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubmitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitResponse) GetSubmit() *SubmitResponseData {
	if x != nil {
		return x.Submit
	}
	return nil
}

type SubmitResponseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Submission ID
	SubmissionId int32 `protobuf:"varint,1,opt,name=submission_id,json=submitId,proto3" json:"submission_id,omitempty"`
	// Status
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Score
	Score int32 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	// Time
	Time int32 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	// Memory
	Memory        int32 `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponseData) Reset() {
	*x = SubmitResponseData{}
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponseData) ProtoMessage() {}

func (x *SubmitResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_judger_server_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponseData.ProtoReflect.Descriptor instead.
func (*SubmitResponseData) Descriptor() ([]byte, []int) {
	return file_proto_core_judger_server_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitResponseData) GetSubmissionId() int32 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *SubmitResponseData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitResponseData) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitResponseData) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SubmitResponseData) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

var File_proto_core_judger_server_v1_server_proto protoreflect.FileDescriptor

const file_proto_core_judger_server_v1_server_proto_rawDesc = "" +
	"\n" +
	"(proto/core/judger_server/v1/server.proto\x12\x10judger_server.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"k\n" +
	"\x14UpsertProblemRequest\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x05R\tproblemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x80\x01\n" +
	"\x15UpsertProblemResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x01(\v2%.judger_server.v1.ProblemResponseDataR\x04data\"4\n" +
	"\x13ProblemResponseData\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x05R\tproblemId\"\xc6\x01\n" +
	"\x14UpsertContestRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\x05R\tcontestId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1f\n" +
	"\vproblem_ids\x18\x06 \x03(\x05R\n" +
	"problemIds\"\x86\x01\n" +
	"\x15UpsertContestResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\acontest\x18\x03 \x01(\v2%.judger_server.v1.ContestResponseDataR\acontest\"4\n" +
	"\x13ContestResponseData\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\x05R\tcontestId\"\xae\x01\n" +
	"\rSubmitRequest\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x05R\tproblemId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12 \n" +
	"\ftest_case_id\x18\x06 \x01(\x05R\n" +
	"testCaseId\"|\n" +
	"\x0eSubmitResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x06submit\x18\x03 \x01(\v2$.judger_server.v1.SubmitResponseDataR\x06submit\"\x8f\x01\n" +
	"\x12SubmitResponseData\x12\x1f\n" +
	"\rsubmission_id\x18\x01 \x01(\x05R\bsubmitId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x05R\x04time\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x05R\x06memory2\xfa\x02\n" +
	"\rJudgerService\x12}\n" +
	"\rUpsertProblem\x12&.judger_server.v1.UpsertProblemRequest\x1a'.judger_server.v1.UpsertProblemResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/problems\x12}\n" +
	"\rUpsertContest\x12&.judger_server.v1.UpsertContestRequest\x1a'.judger_server.v1.UpsertContestResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/contests\x12k\n" +
	"\x06Submit\x12\x1f.judger_server.v1.SubmitRequest\x1a .judger_server.v1.SubmitResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/submissionsB\x19Z\x17proto/rpc/judger_serverb\x06proto3"

var (
	file_proto_core_judger_server_v1_server_proto_rawDescOnce sync.Once
	file_proto_core_judger_server_v1_server_proto_rawDescData []byte
)

func file_proto_core_judger_server_v1_server_proto_rawDescGZIP() []byte {
	file_proto_core_judger_server_v1_server_proto_rawDescOnce.Do(func() {
		file_proto_core_judger_server_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_judger_server_v1_server_proto_rawDesc), len(file_proto_core_judger_server_v1_server_proto_rawDesc)))
	})
	return file_proto_core_judger_server_v1_server_proto_rawDescData
}

var file_proto_core_judger_server_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_core_judger_server_v1_server_proto_goTypes = []any{
	(*UpsertProblemRequest)(nil),  // 0: judger_server.v1.UpsertProblemRequest
	(*UpsertProblemResponse)(nil), // 1: judger_server.v1.UpsertProblemResponse
	(*ProblemResponseData)(nil),   // 2: judger_server.v1.ProblemResponseData
	(*UpsertContestRequest)(nil),  // 3: judger_server.v1.UpsertContestRequest
	(*UpsertContestResponse)(nil), // 4: judger_server.v1.UpsertContestResponse
	(*ContestResponseData)(nil),   // 5: judger_server.v1.ContestResponseData
	(*SubmitRequest)(nil),         // 6: judger_server.v1.SubmitRequest
	(*SubmitResponse)(nil),        // 7: judger_server.v1.SubmitResponse
	(*SubmitResponseData)(nil),    // 8: judger_server.v1.SubmitResponseData
}
var file_proto_core_judger_server_v1_server_proto_depIdxs = []int32{
	2, // 0: judger_server.v1.UpsertProblemResponse.data:type_name -> judger_server.v1.ProblemResponseData
	5, // 1: judger_server.v1.UpsertContestResponse.contest:type_name -> judger_server.v1.ContestResponseData
	8, // 2: judger_server.v1.SubmitResponse.submit:type_name -> judger_server.v1.SubmitResponseData
	0, // 3: judger_server.v1.JudgerService.UpsertProblem:input_type -> judger_server.v1.UpsertProblemRequest
	3, // 4: judger_server.v1.JudgerService.UpsertContest:input_type -> judger_server.v1.UpsertContestRequest
	6, // 5: judger_server.v1.JudgerService.Submit:input_type -> judger_server.v1.SubmitRequest
	1, // 6: judger_server.v1.JudgerService.UpsertProblem:output_type -> judger_server.v1.UpsertProblemResponse
	4, // 7: judger_server.v1.JudgerService.UpsertContest:output_type -> judger_server.v1.UpsertContestResponse
	7, // 8: judger_server.v1.JudgerService.Submit:output_type -> judger_server.v1.SubmitResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_core_judger_server_v1_server_proto_init() }
func file_proto_core_judger_server_v1_server_proto_init() {
	if File_proto_core_judger_server_v1_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_judger_server_v1_server_proto_rawDesc), len(file_proto_core_judger_server_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_judger_server_v1_server_proto_goTypes,
		DependencyIndexes: file_proto_core_judger_server_v1_server_proto_depIdxs,
		MessageInfos:      file_proto_core_judger_server_v1_server_proto_msgTypes,
	}.Build()
	File_proto_core_judger_server_v1_server_proto = out.File
	file_proto_core_judger_server_v1_server_proto_goTypes = nil
	file_proto_core_judger_server_v1_server_proto_depIdxs = nil
}
