load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "models",
    srcs = [
        "problem.go",
        "submission.go",
        "submission_result.go",
    ],
    importpath = "github.com/Nanhtu187/online-judge/src/apps/backend/server/internal/models",
    visibility = ["//src/apps/backend/server:__subpackages__"],
    deps = [
        "@com_github_google_uuid//:uuid",
        "@io_gorm_gorm//:gorm",
    ],
)
